### ISSUE TITLE
NUnit tests

### ISSUE THREAD

**Issue by vpenades** [bepu/bepuphysics2#26]
Just wondering... why not having NUnit tests?

They're very useful to debug parts of a library, and it can also help for learning how to use the library.

**Comment by RossNordby** [comment]
There are tests (e.g. https://github.com/bepu/bepuphysics2/tree/master/Demos/SpecializedTests), just without a proper test harness. The value of setting up a completely automated testing suite (or further, CI) is pretty limited due to the solo contributor nature of the project. This will be re-evaluated as time progresses, of course.

I also want to avoid using correctness tests as educational or demonstrative resources. Those qualities often trade off against each other, so I prefer to have demos specifically built to interactively show how things work. You can see examples of this back in the v1 BEPUphysicsDemos project.  Expect to see more of [these](https://github.com/bepu/bepuphysics2/tree/master/Demos/Demos) as the release approaches.
