### ISSUE TITLE
Determinism test expansion

### ISSUE THREAD

**Issue by RossNordby** [bepu/bepuphysics2#42]
The current test (DeterminismTest) is pretty weak. It covers the universally shared bookkeeping, but fails to capture many complex types.

Probably wise to allow it to evaluate any generic demo.

**Comment by ip** [comment]
Hi! I'm looking for some library for deterministic collision detection for my Unity game. I found the [v. 1 fork](https://github.com/sam-vdp/bepuphysics1int) of BEPUphysics which uses fixed-point math (via  [FixedMath.Net](https://github.com/asik/FixedMath.Net)) but it seems to be abandoned.

It's interesting that you're actively developing version 2 now. Do you plan to support fixed-point determinism? I'm saying fixed-point, because this is probably the only way to reliably get the same results across all platforms.

My use case is following. I want to record game replays on the client side and replaying them on client and server side for these reasons:

- validating replays on server, and then submitting a high-score from the server side, i.e. cheating protection
- online gallery of user replays

Deterministic lock-step approach would allow me to store lots of replays, because I would only need to store inputs.

**Comment by RossNordby** [comment]
Cross platform determinism is something I'd *like* to do, but which I can't realistically devote the necessary time to for the short-medium term at least.

This would have to come after a move towards abstracted SIMD scalars. Right now, all SIMD math is implemented on top of Vector<T> and friends which exposes a small shared set of features. For performance and functionality, I'd like to eventually implement some form of ScalarWide type that is implemented on top of the newer low level intrinsics (https://github.com/dotnet/corefx/issues/22940). With that in place, I could create a fixed point implementation of scalars behind a compilation symbol.

Fixed point would require some more work beyond that, though- all the instances of non-SIMD floats would need to be swapped out too.

All of this requires some codegen improvements in the compiler so that the abstractions would be zero overhead without spewing ifdefs everywhere. That puts a lower bound on the timeline.

**Comment by ip** [comment]
A simpler and easier solution might be code generation, like they do in web development (e.g. TypeScript to JavaScript, also popular in Golang community). [Entitas](https://github.com/sschmid/Entitas-CSharp) ECS library uses this approach as well.

**Comment by RossNordby** [comment]
That's an option I've considered occasionally, but it can introduce some tooling annoyances. The minimal effort and maximum usability path is just having a JIT or other compiler which is able to deal with structs (and ideally operators) with equivalent final assembly to a dedicated code generation pass.

Fortunately, this appears to be an area of focus in the CoreCLR/CoreRT and will probably be addressed before I get around to working on it anyway. Unity is a bit of an unknown, but there are even more issues there. (unless they swap to using the [core runtimes](http://xoofx.com/blog/2018/04/06/porting-unity-to-coreclr/) wink wink nudge wiggly eyebrows come on you know you want to guys)

**Comment by RossNordby** [comment]
Determinism test has been expanded and a whole bunch of bugs have been fixed as of 565713e74af0b8473f5fb518e8feae584768231d.
