### ISSUE TITLE
BodyDescription convenience constructors are inconvenient

### ISSUE THREAD

**Issue by RossNordby** [bepu/bepuphysics2#49]
Too many overloads. Too hard to intuit parameter order. Often less confusing to just use the initializer style, which means the constructors have failed at their only job. Prune out some of them and try to lay out the parameters so adding more optional properties flows naturally.

**Comment by ICanHazCode** [comment]
> ...which means the constructors have failed at their only job.
**facepalm**

Sorry, had to say something.

**Comment by nockawa** [comment]
My 2cts, over the years, I've tried I believe every different way to deal with the matter each time I wrote a library (mostly 3D engines, but other stuffs).

My conclusion regarding .net/C# is to rely on factories to create different "kind" of a given type and to rely on default value as much as possible.

I personally don't consider "constructor failed at their only job" because in the case of an API I like to expose the creation of a user object through a factory and use the constructor for "internal purpose".

I took a quick look at the `BodyDescriptor` struct and you have many public constructors but also many factory alike methods. Why not setting the constructors as private &| internal and also why not naming all the "Create" method more explicitly.

I apologize in advance if it's irrelevant, I'm a big fan of the lib and the author, but I didn't have the chance (yet) to use it. ;)

**Comment by ICanHazCode** [comment]
@nockawa Same, big fan. Though I think he's on the right track with laying out the required parameters and then having everything else as an optional parameter with a default/null. I don't think there is any performance loss that way, since the permutations seem to address the optional parameters.

**Comment by RossNordby** [comment]
At least partially addressed by 1b76b808e3339592f1795d20ebda84f6279cb928.
