### ISSUE TITLE
Observation/Suggestion re: kinematics

### ISSUE THREAD

**Issue by Blwnkl** [bepu/bepuphysics2#51]
Noticed a comment in BodyProperties.cs/123, "//TODO: We may later decide to encode kinematic-ness in the indices held by constraints. That would be somewhat complicated, but if we end up using such an encoding to avoid velocity reads from/writes to kinematics in the solver, we might as well use it for the traversal too."
   A simple approach to efficiency in the solver might be to sort the body elements by their Kinematic property, this having all of the "false" objects appear contiguously, so the 1st check for Kinematic==true to fail would mean the rest of them are going to be true as well, thus allowing exit from the loop.
  Of course, from my perspective, this is just a pseudo-code-thought-experiment!  :)

**Comment by Blwnkl** [comment]
oops...  1st check for Kinematic==true to fail should have said "PASS" :)

**Comment by RossNordby** [comment]
While storing all kinematics contiguously is something I considered for avoiding last second branches, there are additional design constraints. Most importantly, the location of bodies in memory affects cache coherency in the solver. That's why there's a processing stage dedicated to moving bodies and constraints around to maximize adjacency (BodyLayoutOptimizer and ConstraintLayoutOptimizer). If kinematics and dynamics are separated from each other, then practically every dynamic-kinematic constraint data gather will be fully incoherent.

Additionally, most/all of the special casing implied by that flag got removed. There are some cases where it could theoretically be useful, but unifying kinematics and dynamics just simplifies some stuff. Per #44, I'm considering just getting rid of it entirely.
