### ISSUE TITLE
Previous knowledge?

### ISSUE THREAD

**Issue by Bartolomeus-649** [bepu/bepuphysics2#89]
When I look bepuphysics2 and the samples/demos I have come to the conclusion that there's an assumption made that you already are familiar with a lot of terms and concepts and perhaps even have previous experiences with other physics engines.

- What assumptions are made regarding previous experience and knowledge of someone who want to use bepuphysics2?
- Are there any public available resources you should read and understand before you start using bepuphysics2?
- Is there a well established "standard" of how a typical physics engine work, operate and function, and which features one should expect it to support?
- Do Physicengines come in different flavors/types? If so which one do bepuphysics2 belong to?

**Comment by RossNordby** [comment]
>I have come to the conclusion that there's an assumption made that you already are familiar with a lot of terms and concepts and perhaps even have previous experiences with other physics engines.

Yup, that's definitely the case.

>What assumptions are made regarding previous experience and knowledge of someone who want to use bepuphysics2?

In the context of not-physics-specific stuff: be comfortable with low level concepts like memory management. Understand the semantics of value types versus reference types and how the GC is involved. Ideally, be aware of how JIT treats generics and value types when it comes to codegen (unshared implementations).

Basic computational geometry and linear algebra knowledge is also very valuable. If you have that, the remaining physics stuff needed to use the engine is pretty easy. Of course, using a real time physics library of some kind before will help too, since most concepts carry over.

>Are there any public available resources you should read and understand before you start using bepuphysics2?

There are a ton of paths to the requisite knowledge, and there's quite a bit to cover. I don't have a single list of resources, unfortunately. If starting from scratch, googling around for 'linear algebra for game developers' might produce some useful stuff. 3blue1brown has a good series on the fundamentals.

On the more recondite aspects of C# that are (ab)used, I don't know of any good centralized resource. Best advice I can give is to play with it to form a mental model, and perhaps ask when stuck. The C# discord could be helpful there.

>Is there a well established "standard" of how a typical physics engine work, operate and function, and which features one should expect it to support?

Sort of, yes. In the context of performance-focused rigid body engines, most share a common mathematical basis and a similar pipeline. Something along the lines of broad phase collision pair pruning -> narrow phase contact generation -> contact constraint generation -> solve velocity constraints -> integrate positions with new velocities. Lots of variants, but with the same core idea.

You'll often see a lot of the same tradeoffs, too. For example, PGS/SI solvers are very fast, but have a hard time converging with pathologically bad mass ratios. 

>Do Physicengines come in different flavors/types? If so which one do bepuphysics2 belong to?

Yes- not every physics simulator is a rigid body physics simulator, and of rigid body physics simulators, not all of them pick the same tradeoffs. Typically, in games or similar applications, performance is the dominant concern so accuracy is sometimes sacrificed (or it requires opting into non-default features). Havok, PhysX, Bullet, bepuphysics and similar engines fall into this bucket.

Other simulators like MuJoCo focus on articulated structures and accuracy. You see them used frequently in robotics simulation, but very rarely in games.

**Comment by Bartolomeus-649** [comment]
> > Is there a well established "standard" of how a typical physics engine work, operate and function, and which features one should expect it to support?
> 
> Sort of, yes. In the context of performance-focused rigid body engines, most share a common mathematical basis and a similar pipeline. Something along the lines of broad phase collision pair pruning -> narrow phase contact generation -> contact constraint generation -> solve velocity constraints -> integrate positions with new velocities. Lots of variants, but with the same core idea.

So where/how do you find out how to use this process to describe/setup a simulation?

Also, rigid body, if I remember correctly, is when objects don't deform upon collision, right?  So what if you want to make dents when stuff collide?

Where is the "entry point" to the simulation API? And which data types/classes are you supposed to use?  And how/where do you figure out how the physics simulation engine can be used on an architectural level...like what can you do with it, what can you not do and perhaps most important, what shouldn't you do (even if possible), what about simulations without a GUI, or a simulation where you only care about the state/result of the simulation at specific points in time, and then perhaps only the state of one object at that time?

**Comment by RossNordby** [comment]
>So where/how do you find out how to use this process to describe/setup a simulation?

It's more useful as a foundation, since as a mental model it informs a lot of other things about the engine. You don't need to 'set up' the stages yourself (unless you want to make your own ITimestepper)

>Where is the "entry point" to the simulation API? And which data types/classes are you supposed to use? 

I would recommend reading through the getting started documentation to get some high level information:
https://github.com/bepu/bepuphysics2/blob/master/Documentation/GettingStarted.md

Then start playing around in the demos. The [SimpleSelfContainedDemo](https://github.com/bepu/bepuphysics2/blob/master/Demos/Demos/SimpleSelfContainedDemo.cs) shows a simple simulation that doesn't rely on demos types.

>And how/where do you figure out how the physics simulation engine can be used on an architectural level...like what can you do with it, what can you not do and perhaps most important, what shouldn't you do (even if possible)

Best way to get a mental model is to play with it (or other physics engines). The other documentation might also be helpful too, for example:
https://github.com/bepu/bepuphysics2/blob/master/Documentation/StabilityTips.md
https://github.com/bepu/bepuphysics2/blob/master/Documentation/PerformanceTips.md
https://github.com/bepu/bepuphysics2/blob/master/Documentation/QuestionsAndAnswers.md

>what about simulations without a GUI

The physics are completely separate from visualization, so there's no difference.

>simulation where you only care about the state/result of the simulation at specific points in time

You can examine simulation state between timesteps, so if you want to know what the state is at time T, just perform enough timesteps that you simulate up to time T. There are no shortcuts- it's a numerical simulation, so time T depends on every timestep preceding it, and simulation stability is sensitive to timestep duration.

>perhaps only the state of one object at that time?

You can grab references to individual bodies and pull properties from them using Simulation.Bodies.GetBodyReference.

**Comment by RossNordby** [comment]
oops, missed one:
>Also, rigid body, if I remember correctly, is when objects don't deform upon collision, right? So what if you want to make dents when stuff collide?

Correct, rigid body physics engines don't handle deformation. So, if you want dents, rigid body physics engines aren't the right tool. You could make them strictly graphical or use a deformable simulator. Notably, you CAN link a ton of rigid bodies together with constraints to make something like a deformable body (see the NewtDemo or ClothDemo), but that's obviously going to come with a price much higher than single rigid bodies.

**Comment by Bartolomeus-649** [comment]
> t's a numerical simulation, so time T depends on every timestep preceding it
So I can't just set up the initial state and then ask for the state at some arbitrary time in the future?

Is there different kinds of simulations which is not numerical?
With a numerical simulation, is it possible to have different length o the time you step forward? Can the simulation engine provide a "suggested" amount of time to step forward based on the current state of the simulation....so if, for example, the time decrease when objects get closer to each other and there's risk of collision and stuff, and increase when there's less things going on?

**Comment by RossNordby** [comment]
>So I can't just set up the initial state and then ask for the state at some arbitrary time in the future?
There isn't a single function that does that, no, but you could just call timestep in a loop.

>Is there different kinds of simulations which is not numerical?
Yes- some simple simulations can be expressed analytically. A ballistic trajectory, for example. (There also exist 'numerical' techniques in general that don't necessarily imply a time series dependency, but not so much in the context of gamey physics.)

>Can the simulation engine provide a "suggested" amount of time to step forward based on the current state of the simulation....so if, for example, the time decrease when objects get closer to each other and there's risk of collision and stuff, and increase when there's less things going on?

Automatic adaptive timestepping is, in principle, possible. It's mostly constrained to scientific computing, though. In games, it's usually limited to things like pairwise continuous collision detection or, rarely, simulation island level conservative advancement.

Given the use cases in games and the tradeoffs involved, you'll pretty much always just see top level constant timestep durations. The duration is chosen by the user according to the level of stability of fidelity required for the application, so there's no single 'correct' value for a given simulation. Most simulations will run somewhere between 30hz-100hz. Varying the duration can cause instability and is not recommended.

The [stability tips](https://github.com/bepu/bepuphysics2/blob/master/Documentation/StabilityTips.md) documentation goes into some relevant factors.

**Comment by george-tsiros** [comment]
Hello.

I spend quite a bit of time to write this in a way that doesn't make me sound like an unappreciative freeloader, but i can't find one.

The way you have written the demos makes it very difficult to follow along the source code.

Specifically, i can not find how you read each object's position (after an update). 

program.cs, new demoharness, ok what's it do? Render...
            renderer.Shapes.AddInstances(this.demo.Simulation, this.demo.ThreadDispatcher);
            renderer.Lines.Extract(this.demo.Simulation.Bodies, this.demo.Simulation.Solver, this.demo.Simulation.BroadPhase, this.showConstraints, this.showContacts, this.showBoundingBoxes, this.demo.ThreadDispatcher);

is... that where you get the positions? 
i am sorry, i have no idea not even where this things handles are

**Comment by RossNordby** [comment]
General rule for the demos- just look at the stuff in the Demos/Demos folder. The rest is infrastructure and rendering stuff that mostly isn't related to the physics, or where it is, little effort has been put into making it educational.

Simulation.Bodies.GetBodyReference gets you a reference to a body via its handle. The handle for a body is returned by Simulation.Bodies.Add.

You could also go examine raw body state buffers in the Simulation.Bodies.Sets, though this requires manually looking up the memory location via the Simulation.Bodies.HandleToLocation.

**Comment by george-tsiros** [comment]
I appreciate the quick response and the work you've done on this.

I have little knowledge of the intricacies of physics engines, but if i can, i will help
